name: "install-nodejs"
on: push
jobs:
    Install-nodeJS:
        runs-on: "ubuntu-latest"
        steps:
            - name: "Get Code from Repo"
              uses: actions/checkout@v3
            - name: "installing_nodeJS18"
              uses: actions/setup-node@v4
              with:
                node-version: 18

        