name: Install Node JS
on:
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
jobs:
  install_nodeJS:
    runs-on: "ubuntu-latest"
    steps:
      - name: "downloading the repo to the machine"
        uses: actions/checkout@v3
      - name: "Installing the nodeJS"
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: "print_context"
        run: |
          echo "This workflow was trigger by ${{ github.event_name }}"
          echo "Branch ${{ github.ref }}"

